[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.4"
optimizer = true
gas_reports = ["*"]

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = false
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "preserve"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
